<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>CPU_Emulator</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


	<!-- Add your friend assemblies here -->
	<ItemGroup>
		<!-- This allows the unit tests to access the internal members of this project. -->
		<InternalsVisibleTo Include="CPU Emulator Tests" />
	</ItemGroup>

</Project>
